"""initial migrations

Revision ID: e3af14dbab22
Revises: 
Create Date: 2025-04-09 22:10:32.491863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e3af14dbab22'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hero',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('age', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('secret_name', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_hero_name', 'hero', ['name'], unique=False)
    op.create_index('ix_hero_age', 'hero', ['age'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_hero_age', table_name='hero')
    op.drop_index('ix_hero_name', table_name='hero')
    op.drop_table('hero')
    # ### end Alembic commands ###
